### PR TITLE
Formatted with CSS

### PR DESCRIPTION
**Pull request by BKFighter**
I tried to fit with what you guys had on the rest of the website but also made it a bit more material design. Any suggestions?

### CODE REVIEW

**Comment by skistaddy** [comment]
Looks good to me. +1.

**Comment by BKFighter** [comment]
@bjskistad Was the CSS for the border around the demo box intentionally cut out?

**Comment by skistaddy** [comment]
Idk. I mostly just manage the repos, don't do much of the coding anymore. :P Ask @herohamp.

**Comment by BKFighter** [comment]
_facepalm_ _facepalm_ _facebed_ _facelaptop_ _facefloor_ How can I be so stupid! I never moved those changes from Mozilla Thimble to here. _facepalm_

**Comment by BKFighter** [comment]
I just made a new pull request with the demo code.

**Pull request merged**
