### PR TITLE
Download

### PR DESCRIPTION
**Pull request by RonSkons**
I may have fixed downloading. Feel free to test.

### CODE REVIEW

**Comment by haylinmoore** [comment]
You Rock 10/10

**Comment by RonSkons** [comment]
:)

**Comment by skistaddy** [comment]
OMG You rock. Do you have push access for Newawe?

**Comment by haylinmoore** [comment]
Nope

**Comment by RonSkons** [comment]
Nope.

**Comment by skistaddy** [comment]
@herohamp Should we add him?

**Comment by haylinmoore** [comment]
give him push to this

**Comment by skistaddy** [comment]
K.

**Comment by RonSkons** [comment]
Thanks!
BTW I am working on iOS app.
simulator screen shot may 6 2016 5 13 34 pm

**Comment by skistaddy** [comment]
Thanks!

**Pull request merged**
